### ISSUE TITLE
specify port when us bw2 command line

### ISSUE THREAD

**Issue by kaifeichen** [immesys/bw2#10]
Yo, please allow me specify port when us bw2 command line. right on.

**Comment by immesys** [comment]
Only plebs use ports other than 28589 for OOB

**Comment by immesys** [comment]
Am I correct that you want this because you are too lazy to restart docker container with new exported ports? 

Just joking Kaifei, this will be fixed in alpha2

**Comment by immesys** [comment]
fixed in beta
