### ISSUE TITLE
Curl agent install example does not work

### ISSUE THREAD

**Issue by CJKohler** [immesys/bw2#23]
I tried the 'recommended' curl install on Ubuntu 14.04, see below for the errors.

parallels@ubuntu:~$ uname -a
Linux ubuntu 3.13.0-76-generic #120-Ubuntu SMP Mon Jan 18 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

parallels@ubuntu:~$ **sudo curl get.bw2.io/agent | sh**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5374  100  5374    0     0  23952      0 --:--:-- --:--:-- --:--:-- 23884
 ___    _       _    __
(  _`\ ( )  _  ( ) /'__`\
| (_) )| | ( ) | |(_)  ) )
|  _ <'| | | | | |   /' /
| (_) )| (_/ \_) | /' /( )
(____/'`\___x___/'(_____/'

Automated installer for BOSSWAVE 2.7.6 
Assuming systemd
+ sudo -E sh -c useradd -r -s /usr/sbin/nologin bw2
Checking that ntpd is installed
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libopts25
Suggested packages:
  ntp-doc
The following NEW packages will be installed:
  libopts25 ntp
0 upgraded, 2 newly installed, 0 to remove and 15 not upgraded.
Need to get 477 kB of archives.
After this operation, 1,683 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty/main libopts25 amd64 1:5.18-2ubuntu2 [55.3 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main ntp amd64 1:4.2.6.p5+dfsg-3ubuntu2.14.04.12 [421 kB]
Fetched 477 kB in 1s (345 kB/s)
Selecting previously unselected package libopts25:amd64.
(Reading database ... 223810 files and directories currently installed.)
Preparing to unpack .../libopts25_1%3a5.18-2ubuntu2_amd64.deb ...
Unpacking libopts25:amd64 (1:5.18-2ubuntu2) ...
Selecting previously unselected package ntp.
Preparing to unpack .../ntp_1%3a4.2.6.p5+dfsg-3ubuntu2.14.04.12_amd64.deb ...
Unpacking ntp (1:4.2.6.p5+dfsg-3ubuntu2.14.04.12) ...
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up libopts25:amd64 (1:5.18-2ubuntu2) ...
Setting up ntp (1:4.2.6.p5+dfsg-3ubuntu2.14.04.12) ...
 * Starting NTP server ntpd                                                                                                          [ OK ] 
Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
Processing triggers for ureadahead (0.100.0-16) ...
 * Starting NTP server ntpd                                                                                                          [ OK ] 
NTP status: 
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 tock.doonga.org .INIT.          16 u    -   64    0    0.000    0.000   0.000
 hydrogen.consta .INIT.          16 u    -   64    0    0.000    0.000   0.000
 ewr.liveatc.net .INIT.          16 u    -   64    0    0.000    0.000   0.000
 static-96-244-9 .INIT.          16 u    -   64    0    0.000    0.000   0.000
 chilipepper.can .INIT.          16 u    -   64    0    0.000    0.000   0.000
sh: 1: systemctl: not found
sh: 1: systemctl: not found
sh: 172: [[: not found
update-rc.d: /etc/init.d/bw2: file does not exist
sh: 197: [[: not found
bw2: unrecognized service
Bosswave 2.7.6 installed successfully

parallels@ubuntu:~$ bw2 mke --nopublish -o highroller.ent
Could not connect to local BW2 router: dial tcp 127.0.0.1:28589: getsockopt: connection refused

******************************************
 I also tried running it in a Docker container, I got different errors

 * Starting NTP server ntpd                                                                                                                                                    [ OK ]
NTP status:
ntpq: read: Connection refusedbw2: unrecognized service
sh: 172: [[: not found
sh: 197: [[: not found
 * Starting router bw2                                                                                                                                                         [ OK ]
Bosswave 2.7.6 installed successfully
root@4ead82b9563a:/# bw2 mke --nopublish -o highroller.ent
 ╔╡127.0.0.1:28589 2.7.6 'Klystron'
 ╚╡peers=3 block=349628 age=10963h59m54s
Entity created
Public VK: AZi53--lIGC7KlQV-Z_pD8cnLzBsL-VeKzQFI80yMyI=
wrote key to file highroller.ent

root@4ead82b9563a:/# bw2 inspect highroller.ent
 ╔╡127.0.0.1:28589 2.7.6 'Klystron'
 ╚╡peers=3 block=666279 age=9713h47m15s
┳ Type: Entity key file
┣┳ Entity VK: AZi53--lIGC7KlQV-Z_pD8cnLzBsL-VeKzQFI80yMyI=
┃┣ Signature: valid
┃┣ Registry: ERROR: [512] Chain is too stale
┃┣ Alias: err: [512] Chain is too stale
┃┣ Keypair: ok
┃┣ Balances: ERROR: [512] Chain is too stale
┃┣ Created: 2017-08-23T04:17:18Z
┃┣ Expires: 2017-09-22T04:17:18Z

**Comment by immesys** [comment]
try curling it into `bash` rather than `sh` that will fix the `[[` errors.

**Comment by immesys** [comment]
Also the latter one with "chain is too stale" is normal, you just need to give it a bit of time to catch up on the block chain (maybe 20 minutes depending on your computer)

**Comment by immesys** [comment]
I fixed the readme to recommend bash rather

**Comment by CJKohler** [comment]
Thanks, the chain is too stale error was gone this morning. The problem with Ubuntu 14.04 was that the installer seems to think it needs to use systemd, and that failed. Once I upgrade to Ubuntu 16 it was not a problem anymore. I will try on ubuntu 14.04 with curling into bash and see if that works.
Now I just need to find some Ether to get going. Any recommendation on easy mining?

**Comment by immesys** [comment]
@CJKohler If you send me an account I will transfer you some. Do `bw2 i <yourentity>` and send me account number 0 from under balances.
