### ISSUE TITLE
--outfile parameter not working for 'bw2 mke'

### ISSUE THREAD

**Issue by CJKohler** [immesys/bw2#24]
I followed the readme but when I ran the 'bw2 mke' command, it generate a .key file, not the ns.ent file specified. Should I just rename the .key file to ns.ent and use it that way?
```
root@4ead82b9563a:/# bw2 mke --contact "Christian Kohler <blah@lbl.gov>" --comment "Namespace Authority" -- expiry 1y --outfile ns.ent
 ╔╡127.0.0.1:28589 2.7.6 'Klystron'
 ╚╡peers=3 block=3149441 age=21s
Entity created
Public VK: 9ddlvBNSOJfh_3penRJlRUc8bb0NZTq8B8zmu7mb67U=
wrote key to file .9ddlvBNSOJfh_3penRJlRUc8bb0NZTq8B8zmu7mb67U=.key
Waiting for 1 object(s) to publish
Current BCIP set to 2 confirmation blocks or 20 block timeout
Successfully published Entity 9ddlvBNSOJfh_3penRJlRUc8bb0NZTq8B8zmu7mb67U=
All objects published
```

**Comment by gtfierro** [comment]
You have a space between `--`and `expiry`, which is causing the later arguments to be ignored. If you remove the space, the correct `ns.ent` file will be created.

**Comment by immesys** [comment]
Yep, -- is shorthand for "everything that follows is not a flag argument"

**Comment by immesys** [comment]
Also to answer your question, you should create a new ns.ent because this one will expire in 30d (due to the expiry flag being ignored)

**Comment by CJKohler** [comment]
excellent, thanks for the suggestion. I will fix it
