### ISSUE TITLE
Chain is too stale

### ISSUE THREAD

**Issue by ghamkhari** [immesys/bw2#25]
The command `bw2 inspect  <myaccount>` results in `Chain is too stale` error:  

`┳ Type: Entity key file`
`┣┳ Entity VK: ~~~~~~~~~~ Hidden ~~~~~~~~~~~~~~~~~`
`┃┣ Signature: valid`
`┃┣ Registry: ERROR: [512] Chain is too stale`
`┃┣ Alias: err: [512] Chain is too stale`
`┃┣ Keypair: ok`
`┃┣ Balances: ERROR: [512] Chain is too stale`
`┃┣ Comment: ghamkhari's Development Key`
`┃┣ Created: 2017-07-27T11:40:25-07:00`
`┃┣ Expires: 2067-07-15T10:40:25-08:00`

 How can I fix this?

Also, what are the most up-to-date cold storage tokens that can be redeemed?

**Comment by immesys** [comment]
Hi

This will fix itself, you just need to give it a little bit of time. If you run `bw2 status` it will tell you the current age of your sync with the global chain. Check again in half an hour or so.

Once you are up to date, put the output of bw2 inspect here again, and I can transfer ether to you (so you don't have to worry about cold storage tokens).

BTW the entity VK is the "Verifying Key" which is like a public key, you don't have to hide it.

**Comment by ghamkhari** [comment]
This is the output of `bw2 status` on my system:

` ╔╡172.17.0.1:28589 2.7.6 'Klystron'`
` ╚╡peers=7 block=3459218 age=532h54m19s`
`BW2 Local Router status:`
 `   Peer count: 7`
 `Current block: 3459218`
  `  Seen block: 3459218`
  ` Current age: 532h54m19s`
   ` Difficulty: 131776`

Since both the `Current block` and `Seen block` are the same number `3459218`, my sync has the same age as global chain? But `bw2 inspect <myaccount>` still results in `Chain is too stale`. 

My entity VK is `HsS3zDk49uWdUj9jS4_lyuriwBagqojDJ-vGxQWg17M=`

**Comment by immesys** [comment]
This is not quite up to date yet. The current age will go down to a few seconds when it is up to date. You may have to leave it a bit longer. It's odd that it is taking this long though, what sort of system are you using? How much free memory and disk space do you have?

**Comment by gtfierro** [comment]
Current block is much larger: 3639623, so you don't have the most up to
date block there (current age should be less than a couple minutes,
nominally).

Can you try restarting the agent (`sudo systemctl restart bw2`) and see if
the Seen Block increases to something in the range of 3639000?

On Nov 18, 2017 6:20 PM, "Mahdi Ghamkhari" <notifications@github.com> wrote:

This is the output of bw2 status on my system:

╔╡172.17.0.1:28589 2.7.6 'Klystron'
╚╡peers=7 block=3459218 age=532h54m19s
BW2 Local Router status:
Peer count: 7
Current block: 3459218
Seen block: 3459218
Current age: 532h54m19s
Difficulty: 131776

Since both the Current block and Seen block are the same number 3459218, my
sync has the same age as global chain? But bw2 inspect <myaccount> still
results in Chain is too stale.

My entity VK is HsS3zDk49uWdUj9jS4_lyuriwBagqojDJ-vGxQWg17M=

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/immesys/bw2/issues/25#issuecomment-345486580>, or mute
the thread

**Comment by ghamkhari** [comment]
Gabe, all the output that I showed are for the `castle` linux server that I don't have sudo access on. Would you please issue `sudo systemctl restart bw2` on the server? Actually, both the `Current block` and `Seen block`  are stuck on `3459218` and don't increase. 

Michael, the server I am working on has around 2.5 Tb free disk space and 50 Gb of free RAM.

**Comment by immesys** [comment]
Ah, you should have mentioned you were using castle. That's a bit of a special case. I tweaked some stuff, let me know if it is working in about half an hour

**Comment by ghamkhari** [comment]
`Seen block` is now progressing. Thanks for your help. 

I will share my accounts to get ether after being synced.

**Comment by ghamkhari** [comment]
I still have some ether remained. Here is the output of `bw2 inspect <myaccount>`:

`╔╡172.17.0.1:28589 2.7.6 'Klystron'`
`╚╡peers=20 block=3640223 age=14s`
`┳ Type: Entity key file`
`┣┳ Entity VK: HsS3zDk49uWdUj9jS4_lyuriwBagqojDJ-vGxQWg17M=`
`┃┣ Signature: valid`
`┃┣ Registry: valid`
`┃┣ Alias: ghamkhari`
`┃┣ Keypair: ok`
`┃┣ Balances: `
`┃┃┣  0 (0x41b0ad469858e0a6c1fd903a2268b11c5b29216b) 97.264890 Ξ`
`┃┃┣  1 (0x5ea839e0af3ae6cddc1cee19b96a0fccd0e95182) 0.000000 Ξ`
`┃┃┣  2 (0xe06a176cf4788caafed8c38f6fb66fdb2d2f9c0e) 0.000000 Ξ`
`┃┃┣  3 (0x5d4af14d2a08ec814ef6a315db04e878a1fa61f0) 0.000000 Ξ`
`┃┃┣  4 (0x6db7929948f98738bf13ccae7079c903f7d7fa2c) 0.000000 Ξ`
`┃┃┣  5 (0xb1f4d6f908bfa333324e5702e678d23c68da845a) 0.000000 Ξ`
`┃┃┣  6 (0xd28c93222cfbc5910714be80854cb17471955434) 0.000000 Ξ`
`┃┃┣  7 (0x29687fdc22e2e168b6b7742c74569cbd4f87fef9) 0.000000 Ξ`
`┃┃┣  8 (0x60d6641814c03565a25d27886548f6a68319d5dc) 0.000000 Ξ`
`┃┃┣  9 (0xbdb946ac66c2f912a9d5e1270a0f92d0ce0ae82d) 0.000000 Ξ`
`┃┃┣ 10 (0xda1354265fc6739e47181fdad06dde62eaa959ed) 0.000000 Ξ`
`┃┃┣ 11 (0xc8b8c2b02fc1ed31d67345718b19b905ff708b4e) 0.000000 Ξ`
`┃┃┣ 12 (0xcc6ced7d98c8ef4d5f8d08acb7dbc923a3311a32) 0.000000 Ξ`
`┃┃┣ 13 (0xa45f2cf2719c2a6dccba580262e35ad1aafc06e1) 0.000000 Ξ`
`┃┃┣ 14 (0xdcacf03686831e9da3d74826e8c79e25277ce0ac) 0.000000 Ξ`
`┃┃┣ 15 (0x25140a12cede5b3342133a53169dbc5af90ff0bf) 0.000000 Ξ`
`┃┣ Comment: ghamkhari's Development Key`
`┃┣ Created: 2017-07-27T11:40:25-07:00`
`┃┣ Expires: 2067-07-15T10:40:25-08:00`

**Comment by immesys** [comment]
Cool. Glad everything is sorted.
