### ISSUE TITLE
Could not transact: Insufficient funds

### ISSUE THREAD

**Issue by ghamkhari** [immesys/bw2#26]
Hi,

I am trying to bind my namespace entity to a designated router. So I should update SRV record:

`sudo bw2 usrv --dr /etc/bw2/router.ent --srv  My_IP: My_Port`

This error is given:  

`Error updating SRV record: [506] Could not transact: Insufficient funds for gas * price + value`

My Bankroll has 188 Ether. The system I working on is a virtual machine.

**Comment by immesys** [comment]
Pass the bankroll explicitly, you may have unset your environment variable

**Comment by immesys** [comment]
You will find you need to be root to access `/etc/bw2/router.ent` and when you switch to root your environment variables get reset. So my bet is that it is not using the bankroll you set up. Open this again if that is not the case.
