### ISSUE TITLE
Command to transmit and receive messages on URIs

### ISSUE THREAD

**Issue by ghamkhari** [immesys/bw2#27]
The [REAM.ME](https://github.com/immesys/bw2/blob/dev/README.md) file specifies: 

> Later, we will see how URIs are structured and how to deploy BW services.

Where can I find the docs for the above? 

Let say `Alice.ent` has publish-subscribe access to `Oski.domain/Engineering`, and she has given subscription permission to `Bob.ent` on this URI. What command `Alice.ent` can use to transmit a message on `Oski.domain/Engineering`? What command `Bob.ent` can use to receive the transmitted message on that URI?

**Comment by gtfierro** [comment]
There are some docs available on the [wiki](https://github.com/immesys/bw2/wiki) and some examples of pub/sub using Python [here](https://github.com/SoftwareDefinedBuildings/bw2python/blob/master/examples)
