### ISSUE TITLE
Registry: ERROR: [512] Chain is too stale

### ISSUE THREAD

**Issue by CrissJordanY** [immesys/bw2#31]
Does it still work now?how to solve this error"Registry: ERROR: [512] Chain is too stale"?

**Comment by immesys** [comment]
Hi

No, this version of the code is not supported anymore, I'm afraid. This was an early research prototype. But, there will soon be a commercially supported version of what this prototype evolved into - check out antimatter.io

**Comment by CrissJordanY** [comment]
OK，thank you，I'm doing an experiment right now，the WAVE can run locally using a private blockchain？

**Comment by CrissJordanY** [comment]
OK，thank you,I'm working a experiment on WAVE right now. Is there a free version that can run locally?

**Comment by immesys** [comment]
you will have better luck with this version: https://github.com/immesys/wave
